name: Deploy Flizix Frontend

on:
  push:
    branches:
      - main
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download code from github
        uses: actions/checkout@v5

      - name: Configure Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.19
          cache: 'npm'

      - name: Create .env file
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
          echo "VITE_API_PROXY_TARGET=${{ secrets.VITE_API_PROXY_TARGET }}" >> .env
          echo "VITE_TELEGRAM_BOT_NAME=${{ secrets.VITE_TELEGRAM_BOT_NAME }}" >> .env

      - name: Install dependencies and compile
        run: |
          npm ci --legacy-peer-deps
          npm run build

      - name: Send compiled files to server (SFTP)
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "dist/" # Folder generated by React
          TARGET: "/var/www/flizix/dist/" # Server fodler destination